version: '3'
services:
  nginx:
    image: nginx:latest
    posts:
      - "80:80"
    volumes:
      - .:/django
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfiles
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/django/
    expose:
      - "8000"
