# Generated by Django 3.0 on 2020-12-31 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='diary',
            name='now_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_writer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiaryMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='Diary.Diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
