# Generated by Django 3.0 on 2021-02-01 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diary', '0002_auto_20210131_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='now_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='now_writer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
