# Generated by Django 3.0 on 2021-02-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0002_diarygroup_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarygroup',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='diarygroupmember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Diary.DiaryGroup'),
        ),
    ]
