# Generated by Django 3.0 on 2021-02-01 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diary', '0003_auto_20210201_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='now_writer',
        ),
        migrations.AddField(
            model_name='diary',
            name='now_writer',
            field=models.ManyToManyField(blank=True, null=True, related_name='now_writer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
