# Generated by Django 3.0 on 2021-02-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0005_auto_20210201_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_diary_set', to='Diary.Diary')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_set', to='Diary.DiaryGroup')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
