# Generated by Django 3.0 on 2021-02-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0006_diarygroupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarygroup',
            name='diary',
        ),
    ]
