# Generated by Django 3.0 on 2021-02-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diary', '0007_remove_diarygroup_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='user',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
