# Generated by Django 3.0 on 2021-02-08 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diary', '0008_auto_20210208_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='group_join_flag',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='now_writer',
        ),
        migrations.AddField(
            model_name='diary',
            name='now_writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='now_writers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
