# Generated by Django 3.0 on 2021-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0009_auto_20210208_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='total_page',
            field=models.IntegerField(default=1),
        ),
    ]
