# Generated by Django 3.0 on 2021-02-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0010_auto_20210208_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user',
            new_name='master',
        ),
    ]
