# Generated by Django 3.0 on 2021-02-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diary', '0011_auto_20210208_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymember',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Diary.Diary'),
        ),
        migrations.RemoveField(
            model_name='diarymember',
            name='user',
        ),
        migrations.AddField(
            model_name='diarymember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diarymembers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
