# Generated by Django 3.0 on 2021-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0012_auto_20210208_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='total_page',
            field=models.IntegerField(default=20),
        ),
    ]
