# Generated by Django 3.0 on 2021-02-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarygroup',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
