# Generated by Django 3.0 on 2021-02-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_auto_20210211_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarygroupmember',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Diary.Diary'),
        ),
    ]
