# Generated by Django 3.0.1 on 2021-04-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0005_auto_20210422_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='master',
            new_name='user',
        ),
    ]
