# Generated by Django 3.0.1 on 2021-04-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0006_auto_20210423_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarygroupmember',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='diarygroupmember',
            name='rank',
        ),
    ]
