# Generated by Django 3.0.1 on 2021-05-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0009_auto_20210425_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='cover',
            field=models.IntegerField(default=1),
        ),
    ]
