# Generated by Django 3.0.1 on 2021-05-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0010_diary_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='promise',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
