# Generated by Django 3.0.1 on 2021-05-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0012_auto_20210509_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='Diary.DiaryGroup'),
        ),
        migrations.AlterField(
            model_name='diarygroupmember',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupqwer', to='Diary.Diary'),
        ),
    ]
