# Generated by Django 3.0.1 on 2021-05-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0014_auto_20210516_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryGroupMember',
        ),
    ]
