# Generated by Django 3.0.1 on 2021-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0015_delete_diarygroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymember',
            name='profile_img',
            field=models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpg 파일을 업로드해주세요.', null=True, upload_to='accounts/profile/%Y/%m/%d/%H/%M/%S'),
        ),
    ]
