# Generated by Django 3.0.1 on 2021-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0016_diarymember_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='updated_at',
            new_name='_updated_at',
        ),
        migrations.RenameField(
            model_name='diarygroup',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='diarygroup',
            old_name='updated_at',
            new_name='_updated_at',
        ),
        migrations.RenameField(
            model_name='diarymember',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='diarymember',
            old_name='updated_at',
            new_name='_updated_at',
        ),
        migrations.AlterField(
            model_name='diary',
            name='_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='_updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='diarygroup',
            name='_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='diarygroup',
            name='_updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='diarymember',
            name='_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='diarymember',
            name='_updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='diarymember',
            name='profile_img',
            field=models.ImageField(help_text='48px * 48px 크기의 png/jpg 파일을 업로드해주세요.', null=True, upload_to='accounts/profile/%Y/%m/%d/%H/%M/%S'),
        ),
    ]
