# Generated by Django 3.0.1 on 2021-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0018_diary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
