# Generated by Django 3.0.1 on 2021-05-18 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0015_delete_diarygroupmember'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Diary.Diary'),
        ),
    ]
