# Generated by Django 3.0.1 on 2021-05-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210518_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='d',
        ),
    ]
