# Generated by Django 3.0.1 on 2021-05-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0015_delete_diarygroupmember'),
        ('notification', '0003_remove_notification_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Diary.Diary'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
