# Generated by Django 3.0.1 on 2021-06-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20210521_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
