# Generated by Django 3.0.1 on 2021-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20210623_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='_updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('invite', '새로운 일기장에 초대 받았어요!'), ('drop', ' 님이 탈퇴하셨습니다.')], max_length=100),
        ),
    ]
