# Generated by Django 3.0 on 2021-02-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='안녕하세요', max_length=500),
        ),
    ]
