# Generated by Django 3.0.1 on 2021-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_user_kakao_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_column='username', max_length=100, unique=True),
        ),
    ]
